name: Maven Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Verify
        run: mvn -B clean install
